name: RecRadiko

# ─── オプション ────────────────────────────────────────────────────────────────
options:
  bundleIdPrefix: com.recradiko
  minimumXcodeVersion: "15.0"
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true   # 中間ディレクトリをグループとして表示
  defaultConfig: Debug

# ─── ビルド設定（共通） ────────────────────────────────────────────────────────
settings:
  base:
    SWIFT_VERSION: "5.9"
    DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
  configs:
    Debug:
      # ── 開発時: アドホック署名（Apple ID 不要）────────────────────────────
      # Safari → 開発 → 未署名の拡張機能を許可 を有効にしてから使用する
      CODE_SIGN_STYLE: Manual
      CODE_SIGN_IDENTITY: "-"            # "-" = アドホック署名（ローカルのみ）
      CODE_SIGNING_REQUIRED: "NO"
      ENABLE_HARDENED_RUNTIME: "NO"
    Release:
      # ── 配布時: Apple ID と証明書が必要 ──────────────────────────────────
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: 3KYQYNYN7U
      CODE_SIGN_IDENTITY: "Apple Development"
      ENABLE_HARDENED_RUNTIME: "YES"

# ─── ビルド構成 ────────────────────────────────────────────────────────────────
configs:
  Debug:   debug
  Release: release

# ─── ターゲット ────────────────────────────────────────────────────────────────
targets:

  # ── コンテナアプリ (macOS) ──────────────────────────────────────────────────
  RecRadiko:
    type: application
    platform: macOS
    deploymentTarget: "13.0"

    sources:
      - path: App/Sources

    resources:
      - path: App/Resources

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.recradiko.app
        PRODUCT_NAME: RecRadiko
        # Info.plist をビルド時に自動生成（SwiftUI @main に対応）
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: RecRadiko
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        MARKETING_VERSION: "0.2.0"
        CURRENT_PROJECT_VERSION: "1"

    dependencies:
      - target: RecRadikoExtension   # 拡張機能を App Bundle に埋め込む

  # ── Safari Web Extension ────────────────────────────────────────────────────
  RecRadikoExtension:
    type: app-extension
    platform: macOS
    deploymentTarget: "13.0"

    # Swift ソース（SafariWebExtensionHandler のみ）
    sources:
      - path: Extension/Sources

    # Web Extension リソース（manifest.json, background.js, ...）
    resources:
      - path: Extension/Resources

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.recradiko.app.extension
        PRODUCT_NAME: RecRadikoExtension
        MARKETING_VERSION: "0.2.0"
        CURRENT_PROJECT_VERSION: "1"

    # XcodeGen が Extension/Info.plist を自動生成
    info:
      path: Extension/Info.plist
      properties:
        CFBundleDisplayName: RecRadikoExtension
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.Safari.web-extension
          NSExtensionPrincipalClass: "$(PRODUCT_MODULE_NAME).SafariWebExtensionHandler"
